services:
  - type: web
    name: gps-attendance-viewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: Sun_Database_1
